/*
 * generated by Xtext 2.19.0
 */
package org.xtext.computationalmodelling


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DataflowStandaloneSetup extends DataflowStandaloneSetupGenerated {

	def static void doSetup() {
		new DataflowStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
