/*
 * generated by Xtext 2.19.0
 */
package org.xtext.computationalmodelling


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RegularExpressionsStandaloneSetup extends RegularExpressionsStandaloneSetupGenerated {

	def static void doSetup() {
		new RegularExpressionsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
