/*
 * generated by Xtext 2.36.0
 */
package info.computationalmodeling.lang.tests

import com.google.inject.Inject
import info.computationalmodeling.lang.lineartemporallogic.LTLModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(LinearTemporalLogicInjectorProvider)
class LinearTemporalLogicParsingTest {
	@Inject
	ParseHelper<LTLModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''ltl formula phi = G ( p => F q) 
alphabet {a, b, c, d}
where 
    p = {a, b}
    q = {c, d}''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
