/*
 * generated by Xtext 2.36.0
 */
package info.computationalmodeling.lang.tests

import com.google.inject.Inject
import info.computationalmodeling.lang.maxplusmatrix.MaxPlusMatrixModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(MaxPlusMatrixInjectorProvider)
class MaxPlusMatrixParsingTest {
	@Inject
	ParseHelper<MaxPlusMatrixModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''max-plus model MPModel:
matrices
A =
[
	[ -inf   -inf  -10  7 15]
	[ 1 -inf -inf -inf 3 ]
    [-inf 3 -inf -inf -inf]
    [-inf -4 5 -inf 20]
    [-inf -inf -inf -inf -1]
]''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
