/*
 * generated by Xtext 2.36.0
 */
package info.computationalmodeling.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MarkovChainsStandaloneSetup extends MarkovChainsStandaloneSetupGenerated {

	def static void doSetup() {
		new MarkovChainsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
