/*
 * generated by Xtext 2.26.0
 */
package info.computationalmodeling.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FiniteStateAutomataStandaloneSetup extends FiniteStateAutomataStandaloneSetupGenerated {

	def static void doSetup() {
		new FiniteStateAutomataStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
