#!/bin/bash

cd ./info.computationalmodeling.lang.parent
./gradlew installdist
cp -R ./info.computationalmodeling.lang.ide/build/install/info.computationalmodeling.lang.ide /output/

cd ../info.computationalmodeling.lang.codegen.parent
./gradlew installdist
cp -R ./info.computationalmodeling.lang.codegen.compiler/build/install/info.computationalmodeling.lang.codegen.compiler /output/


