/*
 * generated by Xtext 2.29.0
 */
package info.computationalmodeling.lang.ide


/**
 * Use this class to register ide components.
 */
class MarkovChainsIdeModule extends AbstractMarkovChainsIdeModule {
}
