/*
 * generated by Xtext 2.20.0
 */
package org.xtext.computationalmodelling.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.xtext.computationalmodelling.DataflowRuntimeModule;
import org.xtext.computationalmodelling.DataflowStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ComputationalModellingIdeSetup extends DataflowStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DataflowRuntimeModule(), new ComputationalModellingIdeModule()));
	}
	
}
