/*
 * generated by Xtext 2.20.0
 */
package org.xtext.computationalmodelling.ide;


/**
 * Use this class to register ide components.
 */
public class ComputationalModellingIdeModule extends AbstractDataflowIdeModule {
}
