/*
 * generated by Xtext 2.26.0
 */
package info.computationalmodeling.lang


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RegularExpressionsRuntimeModule extends AbstractRegularExpressionsRuntimeModule {
}
