/*
 * generated by Xtext 2.19.0
 */
package org.xtext.computationalmodelling.ide


/**
 * Use this class to register ide components.
 */
class LinearTemporalLogicIdeModule extends AbstractLinearTemporalLogicIdeModule {
}
